name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: gcc *.c -o escape-from-castle-udolpho

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: escape-from-castle-udolpho-${{ matrix.os }}
          path: |
            escape-from-castle-udolpho
            escape-from-castle-udolpho.exe